name: Docker Image CI

on:
  push:
    branches:
    - main
  workflow_dispatch:
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.ACR_USERNAME }}
        # Container registry password
        password: ${{ secrets.ACR_PASSWORD }}
        # Container registry server url
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env: 
        IMAGENAME: sample-app-aoai-chatgpt
      run:         
        docker build . --file WebApp.Dockerfile --tag ${{ secrets.ACR_LOGIN_SERVER }}/{{ env.IMAGENAME }}:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag ${{ secrets.ACR_LOGIN_SERVER }}/{{ env.IMAGENAME }}:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER ${{ secrets.ACR_LOGIN_SERVER }}/{{ env.IMAGENAME }}:latest;
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/{{ env.IMAGENAME }}:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/{{ env.IMAGENAME }}:latest;
      
